'area:code':
 - changed-files:
    - any-glob-to-any-file:
      - '.claude-plugin/**/*'
      - 'plugins/**/*'

'area:style':
 - changed-files:
    - any-glob-to-any-file:
      - '**/.editorconfig'
      - '**/.markdownlint-cli2.jsonc'
      - 'ruff.toml'
      - 'pyrightconfig.json'

'area:repo':
 - changed-files:
    - any-glob-to-any-file:
      - '.github/*.yml'
      - '.github/**/*.md'
      - CODEOWNERS
      - '.github/CODEOWNERS'

'area:ci':
 - changed-files:
    - any-glob-to-any-file:
      - '.github/workflows/**/*'
      - '.github/problem-matchers/**/*'

'area:build':
 - changed-files:
    - any-glob-to-any-file:
      - 'Makefile'
      - '**/plugin.mk'
      - 'requirements-dev.txt'

'area:deps':
 - changed-files:
    - any-glob-to-any-file:
      - 'requirements-dev.txt'

'area:docs':
 - changed-files:
    - any-glob-to-any-file:
      - 'docs/**/*'
      - '.all-contributorsrc'
      - '**/CHANGELOG.md'
      - '**/LICENSE'
      - '**/README.md'
      - '**/THIRD-PARTY-NOTICES'
